### ISSUE TITLE
Supporting ESP8266

### ISSUE THREAD

**Issue by Yariv-h** [zombodotcom/esp32-Async-FastLED-Audio#8]
Hello,

was wondering if you had the chance to test it over esp8266? seems like its too slow for that which it's quite an odd. 

I was able to upload and simple fft code with adc reading to pro micro, so this board should be able to handle FFT as well.

So... just wondering if you had the chance to tests it :)

**Comment by zombodotcom** [comment]
jason coon already has an esp8266 version with and without audio

https://github.com/jasoncoon/esp8266-fastled-audio

Heres FFT for esp8266 should be similar. 
https://github.com/G6EJD/ESP32-8266-Audio-Spectrum-Display
