### ISSUE TITLE
8266?

### ISSUE THREAD

**Issue by jordanadania** [zombodotcom/esp32-Async-FastLED-Audio#9]
Would this work on my 8266's lying around?

Or do I have to go pull the 32 out of my car?

Or just buy another one...

I saw someone asked this in closed issues, but you referred them to jasoncoon's work and I thought that required a router.

Thank you!

**Comment by zombodotcom** [comment]
I don't think so. I am using libraries specific to the esp32 like the sta and ap mode. with some modifications to the wifi.h file you could remove the AP+STA mode and change it to just AP mode.

but then you would have to deal with changing the analog pin reading. and then you would have to make sure that the esp8266 has enough processing power to do the FFT.

I really suggest using jason coon's esp8266 wifi server

or using my own edited version of his from a while ago.

https://github.com/zombodotcom/ESP8266FastLedAudioMSGEQ7/blob/master/Nodemcu_Amica_esp8266_WebserverAudio.ino

Notice there are a few files in there, but it also has **### kMATRIX**

so its supposed to be in a matrix. it should work fine i think without it being in a matrix and just 1 led strip. 

i used that I think for my LED top HAT
